{% set version = "1.9" %}

package:
  name: topojson
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/topojson/topojson-{{ version }}.tar.gz
  sha256: 5a8389ff576d5540660d4430dab56fcadef7c1f90b9f1aa486b1cb140033ff3b

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit
  run:
    - python >={{ python_min }}
    - numpy
    - shapely
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - topojson

about:
  home: "https://github.com/mattijn/topojson"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "topojson - a powerful library to encode spatial data as topology in Python!"
  doc_url: https://mattijn.github.io/topojson
  dev_url: https://github.com/mattijn/topojson

extra:
  recipe-maintainers:
    - mattijn
